import {activeLayers} from './layers.js';
let ctx=null,master=null,musicBus=null,baseBus=null,layerBuses=[],sfxBus=null,filter=null,scheduler=null,nextBeat=0,bpm=110,beatNumber=0,layerCount=0,volume=.65,menuOsc=[];
export function unlockAudio(){if(!ctx){const AudioContextType=globalThis.AudioContext||globalThis.webkitAudioContext;if(!AudioContextType)return null;try{ctx=new AudioContextType();master=ctx.createGain();master.gain.value=volume;master.connect(ctx.destination);musicBus=ctx.createGain();musicBus.connect(master);filter=ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=19000;filter.connect(musicBus);baseBus=ctx.createGain();baseBus.gain.value=.55;baseBus.connect(filter);layerBuses=Array.from({length:4},()=>{const bus=ctx.createGain();bus.gain.value=0;bus.connect(filter);return bus;});sfxBus=ctx.createGain();sfxBus.gain.value=.7;sfxBus.connect(master);}catch{ctx=null;master=null;musicBus=null;baseBus=null;layerBuses=[];sfxBus=null;filter=null;return null;}}if(ctx.state==='suspended')ctx.resume().catch(()=>{});return ctx;}
function tone(freq,time,duration,{type='sine',gain=.08,decay=true,bus=sfxBus,detune=0}={}){if(!ctx||!bus)return;const osc=ctx.createOscillator(),amp=ctx.createGain();osc.type=type;osc.frequency.setValueAtTime(freq,time);osc.detune.value=detune;amp.gain.setValueAtTime(.0001,time);amp.gain.exponentialRampToValueAtTime(Math.max(.0002,gain),time+.008);if(decay){amp.gain.exponentialRampToValueAtTime(.0001,time+duration);}osc.connect(amp);amp.connect(bus);osc.start(time);osc.stop(time+duration+.03);}
function kick(time){const osc=ctx.createOscillator(),amp=ctx.createGain();osc.type='sine';osc.frequency.setValueAtTime(115,time);osc.frequency.exponentialRampToValueAtTime(43,time+.14);amp.gain.setValueAtTime(.0001,time);amp.gain.exponentialRampToValueAtTime(.32,time+.006);amp.gain.exponentialRampToValueAtTime(.0001,time+.19);osc.connect(amp);amp.connect(baseBus);osc.start(time);osc.stop(time+.21);}
function hat(time,accent=false){const buffer=ctx.createBuffer(1,Math.ceil(ctx.sampleRate*.035),ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*(1-i/data.length);const src=ctx.createBufferSource(),amp=ctx.createGain(),high=ctx.createBiquadFilter();high.type='highpass';high.frequency.value=7200;src.buffer=buffer;amp.gain.setValueAtTime(accent?.045:.025,time);amp.gain.exponentialRampToValueAtTime(.0001,time+.032);src.connect(high);high.connect(amp);amp.connect(baseBus);src.start(time);}
function bass(time,beat){const scale=[55,65.41,73.42,82.41,98,110],freq=scale[(beat*3+Math.floor(beat/4))%scale.length];tone(freq,time,.28,{type:'triangle',gain:.10,bus:baseBus});}
function scheduleBeat(time,beat){if(beat%4===0)kick(time);if(beat%2===0)bass(time,beat);hat(time,true);const eighth=time+(60/bpm/2);setTimeout(()=>{if(ctx&&scheduler!==null&&Math.abs(ctx.currentTime-eighth)<.25)hat(eighth,false);},Math.max(0,(eighth-ctx.currentTime)*1000));if(layerCount>=1&&beat%2===0){const chord=[220,261.63,329.63];for(const f of chord)tone(f,time,1.7,{type:'sine',gain:.035,bus:layerBuses[0]});}if(layerCount>=2){const notes=[220,261.63,293.66,329.63,392];for(let i=0;i<4;i++)tone(notes[(beat*2+i)%notes.length],time+i*60/bpm/4,.09,{type:'triangle',gain:.018,bus:layerBuses[1]});}if(layerCount>=4){const chord=[110,164.81,220];for(const f of chord)tone(f,time,1.9,{type:'sawtooth',gain:.012,bus:layerBuses[3]});}}
export function startMenuHum(){if(!unlockAudio()||menuOsc.length)return;for(const f of[55,82.41]){const osc=ctx.createOscillator(),amp=ctx.createGain();osc.type='sine';osc.frequency.value=f;amp.gain.value=.007;osc.connect(amp);amp.connect(musicBus);osc.start();menuOsc.push({osc,amp});}}
export function stopMenuHum(){for(const node of menuOsc){try{node.osc.stop();}catch{}}menuOsc=[];}
export function startBacking(songBpm,offsetMs=0){if(!unlockAudio())return;stopBacking();bpm=songBpm;const beatSec=60/bpm,phase=(offsetMs/1000)%beatSec;nextBeat=ctx.currentTime+Math.max(.015,beatSec-phase);beatNumber=Math.floor(offsetMs/1000/beatSec);scheduler=setInterval(()=>{if(!ctx||scheduler===null)return;while(nextBeat<ctx.currentTime+.12){scheduleBeat(nextBeat,beatNumber++);nextBeat+=beatSec;}},25);}
export function stopBacking(){if(scheduler!==null){clearInterval(scheduler);scheduler=null;}}
export function setLayers(combo){if(!ctx)return;layerCount=activeLayers(combo);const now=ctx.currentTime,target=layerCount;layerBuses.forEach((bus,index)=>{const value=index<target?([.16,.17,.1,.1][index]):0;bus.gain.cancelScheduledValues(now);bus.gain.setTargetAtTime(value,now+.03,.09);});}
export function dropout(){if(!ctx)return;const now=ctx.currentTime;for(const bus of layerBuses){bus.gain.cancelScheduledValues(now);bus.gain.setTargetAtTime(0,now,.06);}filter.frequency.cancelScheduledValues(now);filter.frequency.setValueAtTime(19000,now);filter.frequency.linearRampToValueAtTime(900,now+.12);filter.frequency.linearRampToValueAtTime(19000,now+.72);layerCount=0;}
export function playJudgement(kind,lane=0){if(!ctx)return;const notes=[261.63,293.66,329.63,392,440,523.25],time=ctx.currentTime;const f=notes[lane%notes.length];if(kind==='perfect'){tone(f,time,.2,{type:'sine',gain:.13});tone(f*2,time,.16,{type:'triangle',gain:.04,bus:layerCount>=3?layerBuses[2]:sfxBus,detune:-7});if(layerCount>=3)tone(f*2,time,.16,{type:'triangle',gain:.035,bus:layerBuses[2],detune:7});}else if(kind==='great')tone(f,time,.17,{type:'triangle',gain:.09});else if(kind==='good')tone(f*.75,time,.13,{type:'sine',gain:.06});else tone(110,time,.18,{type:'sawtooth',gain:.035});}
export function playUi(){if(!ctx)return;tone(540,ctx.currentTime,.045,{type:'sine',gain:.018});}
export function playMilestone(){if(!ctx)return;const now=ctx.currentTime;[523.25,659.25,783.99].forEach((f,i)=>tone(f,now+i*.075,.28,{type:'triangle',gain:.065}));}
export function setVolume(value){volume=Math.max(0,Math.min(1,value));if(master)master.gain.setTargetAtTime(volume,ctx.currentTime,.04);}
export function audioTime(){return ctx?.currentTime||0;}
