export const JUDGEMENT_WINDOWS=Object.freeze({perfect:45,great:90,good:150});
export function createEngine({chart,difficulty='easy',settings={}}){return{chart,difficulty,notes:chart.notes.map((note,index)=>({...note,index,judged:false})),score:0,combo:0,maxCombo:0,health:100,healthMin:100,perfect:0,great:0,good:0,miss:0,judgedCount:0,weightedHits:0,perfectStreak:0,perfectStreakMax:0,errors:[],missStreak:0,lastMissAt:-Infinity,scoreAfter:Array(chart.notes.length).fill(null),finished:false,assist:!!settings.assist};}
export function activeLayers(combo){return combo>=100?4:combo>=50?3:combo>=25?2:combo>=10?1:0;}
export function hit(engine,lane,pressTime,offset=0){if(engine.finished)return{kind:'none'};const time=pressTime-offset,window=JUDGEMENT_WINDOWS.good*(engine.assist?1.5:1);let best=null,bestAbs=Infinity;for(const note of engine.notes){if(note.judged||note.lane!==lane)continue;const error=time-note.t,abs=Math.abs(error);if(abs<=window&&abs<bestAbs){best=note;bestAbs=abs;}}
  if(!best){return{kind:'empty'};}const error=time-best.t,abs=Math.abs(error),kind=abs<=JUDGEMENT_WINDOWS.perfect?'perfect':abs<=JUDGEMENT_WINDOWS.great?'great':'good',weight={perfect:1,great:.7,good:.4}[kind],base={perfect:300,great:200,good:100}[kind],multiplier=Math.min(4,1+Math.floor(engine.combo/10));best.judged=true;best.kind=kind;best.error=error;engine[kind]++;engine.judgedCount++;engine.combo++;engine.maxCombo=Math.max(engine.maxCombo,engine.combo);engine.perfectStreak=kind==='perfect'?engine.perfectStreak+1:0;engine.perfectStreakMax=Math.max(engine.perfectStreakMax,engine.perfectStreak);engine.weightedHits+=weight;engine.errors.push(error);engine.score+=base*multiplier;engine.health=Math.min(100,engine.health+(kind==='perfect'?1.15:kind==='great'?.7:.25));engine.healthMin=Math.min(engine.healthMin,engine.health);engine.scoreAfter[best.index]=engine.score;return{kind,error,lane,combo:engine.combo,multiplier,note:best};}
export function tick(engine,time){if(engine.finished)return[];const misses=[];for(const note of engine.notes){if(note.judged)continue;const late=time-note.t;if(late>JUDGEMENT_WINDOWS.good*(engine.assist?1.5:1)){note.judged=true;note.kind='miss';engine.miss++;engine.judgedCount++;engine.missStreak++;engine.lastMissAt=time;engine.combo=0;engine.perfectStreak=0;const drain=({easy:5,normal:7,hard:9,expert:12}[engine.difficulty]||5)*(engine.assist ? .6 : 1);engine.health=Math.max(0,engine.health-drain);engine.healthMin=Math.min(engine.healthMin,engine.health);engine.scoreAfter[note.index]=engine.score;misses.push(note);}}if(engine.health<=0&&!engine.assist)engine.finished=true;return misses;}
export function accuracy(engine){return engine.judgedCount?100*(engine.perfect+engine.great+engine.good)/engine.judgedCount:0;}
export function grade(engine){const a=accuracy(engine);return a>=98?'S':a>=90?'A':a>=80?'B':a>=65?'C':'D';}
export function summary(engine){const acc=accuracy(engine),cleared=engine.assist||engine.health>0&&engine.miss<engine.notes.length,stars=cleared?(acc>=88?2:1):0;return{score:engine.score,accuracy:acc,grade:grade(engine),maxCombo:engine.maxCombo,perfect:engine.perfect,great:engine.great,good:engine.good,miss:engine.miss,healthMin:engine.healthMin,weightedHits:engine.weightedHits,totalNotes:engine.notes.length,cleared,stars,errors:engine.errors.slice(),scoreAfter:engine.scoreAfter.slice()};}
