import {buildCircuit,hashSeed} from './sim.js';
import {generateChart,DIFFICULTIES} from './chart.js';
import {createEngine,hit,tick,accuracy,summary} from './engine.js';
import {activeLayers} from './layers.js';
import {flyMood} from './fly-mood.js';
import {loadProfile,saveProfile} from './storage.js';
import {discover,levelForXp,levelTitle,awardXp,updateStreak} from './progress.js';
import {runSimulation} from './simulation.js';
import {unlockAudio,startMenuHum,stopMenuHum,startBacking,stopBacking,setLayers,dropout,playJudgement,playUi,playMilestone,setVolume,audioTime} from './audio.js';

const $=id=>document.getElementById(id),LANE_KEYS=['s','d','f','j','k','l'],LANE_COLORS=['#c7ff4f','#a48bff','#ff78b5','#6ae4d0','#ffc36d','#7ec5ff'];
let circuitJson,circuit,songs=[],profile=loadProfile(),selectedSong=null,selectedDifficulty='easy',currentProgram=null,simResult=null,chart=null,engine=null,mode='campaign',dailyDate='',animationFrame=0,lastFrame=0,lastStageWidth=0,lastStageHeight=0,graphCache=null,stageParticles=[],hitFlash=Array(6).fill(0),songStartPerf=0,pauseAt=0,objectiveDone=false,coachSeen={},preparationId=0,simulationController=null;const runCache=new Map();
const stage=$('stage'),ctx=stage.getContext('2d'),flyCanvas=$('flyCanvas'),flyCtx=flyCanvas.getContext('2d');
const ACHIEVEMENTS=[
  {id:'first_flight',title:'First Flight',copy:'Clear your first campaign signal.',test:p=>songs.some(s=>Object.values(p.cleared[s.id]||{}).some(Boolean))},
  {id:'six_signals',title:'Six Signals',copy:'Clear every campaign chapter.',test:p=>songs.length>0&&songs.every(s=>Object.values(p.cleared[s.id]||{}).some(Boolean))},
  {id:'hard_wings',title:'Hard Wings',copy:'Clear a signal on Hard or Expert.',test:p=>songs.some(s=>p.cleared[s.id]?.hard||p.cleared[s.id]?.expert)},
  {id:'clean_circuit',title:'Clean Circuit',copy:'Finish a full signal with no misses.',test:p=>(p.lifetime.perfectRuns||0)>0},
  {id:'combo_50',title:'Fifty-Fold',copy:'Build a 50-note combo in one run.',test:p=>(p.lifetime.bestCombo||0)>=50},
  {id:'atlas_12',title:'Field Naturalist',copy:'Discover 12 specimen entries.',test:p=>p.atlas.discovered.length>=12},
  {id:'daily_3',title:'Three-Day Flight',copy:'Keep a three-day Daily Brain streak.',test:p=>p.streak.count>=3}
];
function toast(message){const el=$('toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2300);}
function fmt(n){return Math.max(0,Math.round(n)).toLocaleString('en-US');}
function buttonTone(){unlockAudio();playUi();}
function campaignStars(){return Object.values(profile.stars).reduce((sum,byDiff)=>sum+Math.max(0,...Object.values(byDiff||{})),0);}
function highestDifficulty(song){const s=profile.cleared[song.id]||{};return s.expert?'expert':s.hard?'hard':s.normal?'normal':'easy';}
function unlockedDifficulty(){return true;}
function canAccessSong(){return true;}
function nextSongIndex(){const i=songs.findIndex((song,index)=>canAccessSong(index)&&!Object.values(profile.cleared[song.id]||{}).some(Boolean));return i<0?songs.length-1:i;}
function renderHome(){const stars=campaignStars(),clears=Object.values(profile.cleared).filter(v=>Object.values(v||{}).some(Boolean)).length,spikes=profile.lifetime.spikes||0;
  $('statSongs').textContent=String(profile.lifetime.songs||0).padStart(2,'0');$('statSpikes').textContent=fmt(spikes).padStart(3,'0');$('statBest').textContent=profile.bestScore?fmt(profile.bestScore):'—';$('starTotal').textContent=stars;$('campaignFill').style.width=`${Math.min(100,stars/18*100)}%`;$('topLevel').textContent=`${levelTitle(profile.level).toUpperCase()} · LV ${String(profile.level).padStart(2,'0')}`;
  $('continueText').textContent=!profile.seenTutorial?'START THE FIELD GUIDE':`CONTINUE · ${songs[nextSongIndex()]?.title.toUpperCase()||'PLAY AGAIN'}`;$('atlasCount').textContent=String(profile.atlas.discovered.length).padStart(2,'0');$('achievementCount').textContent=String(profile.achievements.length).padStart(2,'0');
  $('songGrid').replaceChildren();songs.forEach((song,index)=>{const card=document.createElement('button');card.type='button';card.className=`song-card${canAccessSong(index)?'':' locked'}${selectedSong?.id===song.id?' active':''}${Object.values(profile.cleared[song.id]||{}).some(Boolean)?' cleared':''}`;card.style.setProperty('--card-accent',LANE_COLORS[index%LANE_COLORS.length]);card.disabled=!canAccessSong(index);card.setAttribute('aria-label',`${song.chapter} ${song.title}${card.disabled?', locked':''}`);
    const num=document.createElement('span');num.className='song-number';num.textContent=song.chapter;
    const title=document.createElement('span');title.className='song-title';title.textContent=song.title;
    const sub=document.createElement('span');sub.className='song-subtitle';sub.textContent=song.subtitle;
    const star=document.createElement('span');star.className='song-stars';const max=Math.max(0,...Object.values(profile.stars[song.id]||{}));for(let i=0;i<3;i++){const s=document.createElement('i');s.textContent='✦';if(i<max)s.className='earned';star.append(s);}
    card.append(num,title,sub,star);if(card.disabled){const lock=document.createElement('span');lock.className='lock';lock.textContent='◌';card.append(lock);}else{const play=document.createElement('span');play.className='song-play';play.textContent='↗';card.append(play);card.addEventListener('click',()=>openSong(song,index));} $('songGrid').append(card);
  });
  const known=[...new Set(circuitJson.neurons.cellType.filter(Boolean))],found=profile.atlas.discovered.length;$('atlasProgress').textContent=`${found} / ${known.length}`;$('atlasList').replaceChildren();for(const type of known.slice(0,80)){const item=document.createElement('div');item.className=`atlas-item${profile.atlas.discovered.includes(type)?'':' locked'}`;const name=document.createElement('strong');name.textContent=profile.atlas.discovered.includes(type)?type:'???';const meta=document.createElement('span');const i=circuitJson.neurons.cellType.indexOf(type);meta.textContent=profile.atlas.discovered.includes(type)?`${circuitJson.neurons.cls[i]} · ${circuitJson.neurons.side[i]} · ${circuitJson.neurons.sign[i]<0?'inhibitory':'excitatory'}`:'Play a run to discover';item.append(name,meta);$('atlasList').append(item);}
  if(circuitJson.meta.source!=='flywire')$('demoBanner').hidden=false;
}
function renderCareer(){const unlocked=new Set(profile.achievements);$('careerSummary').textContent=`${levelTitle(profile.level)} · level ${profile.level} · ${fmt(profile.xp)} XP · ${profile.streak.count} day Daily streak · ${unlocked.size}/${ACHIEVEMENTS.length} medals`;const list=$('achievementList');list.replaceChildren();for(const badge of ACHIEVEMENTS){const earned=unlocked.has(badge.id),row=document.createElement('article');row.className=`achievement-card${earned?' earned':''}`;const icon=document.createElement('span');icon.className='achievement-icon';icon.textContent=earned?'✦':'◇';const body=document.createElement('div'),title=document.createElement('strong'),copy=document.createElement('p');title.textContent=badge.title;copy.textContent=earned?badge.copy:`LOCKED · ${badge.copy}`;body.append(title,copy);row.append(icon,body);list.append(row);}}
function openSong(song,index){selectedSong=song;mode='campaign';$('pickChapter').textContent=`CHAPTER ${song.chapter} / SELECT DIFFICULTY`;$('pickSongTitle').textContent=song.title;$('pickStory').textContent=song.story;$('difficultyChoices').replaceChildren();for(const[diff,rules]of Object.entries(DIFFICULTIES)){const button=document.createElement('button');button.type='button';button.className='difficulty-choice';button.setAttribute('aria-pressed',String(diff===selectedDifficulty));button.disabled=!unlockedDifficulty(song,diff);button.textContent=rules.label;const small=document.createElement('small');small.textContent=`${rules.lanes} LANES · ${rules.targetNps.toFixed(1)} NOTES/S · ${Math.round(rules.approachMs)}ms`;button.append(small);if(!button.disabled)button.addEventListener('click',()=>{selectedDifficulty=diff;for(const el of $('difficultyChoices').children)el.setAttribute('aria-pressed',String(el===button));$('difficultyBadge').textContent=`${rules.label} · ${rules.lanes} LANES`;});$('difficultyChoices').append(button);}selectedDifficulty=highestDifficulty(song);for(const b of $('difficultyChoices').children){b.setAttribute('aria-pressed',String(b.textContent.startsWith(DIFFICULTIES[selectedDifficulty].label)));}buttonTone();$('difficultyDialog').showModal();}
function programForSong(song,seed=undefined,tracks=song.tracks){return{v:1,seed:seed??hashSeed(song.id,'neuron-beat-v1'),durationMs:song.durationMs,bpm:song.bpm,tracks};}
const tutorialSteps=[
  {title:'Find the signal.',body:'A stimulus wakes this tiny synthetic brain. Its changing activity becomes a rhythm. You are the fly: listen for a pattern, then answer it with your hands.',visual:'signal'},
  {title:'Choose a lane.',body:'Each falling signal belongs to a lane. Easy uses S, D, F, J. Normal, Hard, and Expert use all six keys, S, D, F, J, K, L, from left to right. Tap the matching pad on screen if you prefer.',visual:'lanes'},
  {title:'Meet the line.',body:'Watch a signal travel downward. Hit its key as it crosses the glowing lime line. Perfect is within 45 ms, Great within 90 ms, and Good within 150 ms.',visual:'timing'},
  {title:'Build neural sync.',body:'Accurate hits grow your combo and bring the soundtrack to life: PAD at 10, ARP at 25, OCTAVE at 50, and CHOIR at 100. Misses break the streak and drain stability; at zero, the run ends.',visual:'combo'},
  {title:'Read your mission.',body:'Every song has a personal objective shown below the playfield. Complete it for a bonus star. You can replay any signal on any difficulty; stars are rewards and progress markers, never access gates.',visual:'mission'},
  {title:'Make it yours.',body:'Retry with R, pause with Esc, or pause from the top-right button. Practice mode widens timing and removes game over, but disables stars. Adjust volume, motion, haptics, and input offset in Settings. Then choose a signal and set your own pace.',visual:'finish'}
];
let tutorialStep=0,tutorialStartsRun=false;
function renderTutorial(){const step=tutorialSteps[tutorialStep];$('tutorialCount').textContent=`${String(tutorialStep+1).padStart(2,'0')} / ${String(tutorialSteps.length).padStart(2,'0')}`;$('tutorialTitle').textContent=step.title;$('tutorialBody').textContent=step.body;$('tutorialVisual').dataset.tutorialVisual=step.visual;$('tutorialPrev').disabled=tutorialStep===0;$('tutorialNext').hidden=tutorialStep===tutorialSteps.length-1;$('tutorialStart').hidden=tutorialStep!==tutorialSteps.length-1;$('tutorialSkip').textContent=tutorialStartsRun?'SKIP GUIDE · START RUN':'CLOSE GUIDE';$('tutorialSteps').replaceChildren();tutorialSteps.forEach((item,index)=>{const button=document.createElement('button');button.type='button';button.className=`tutorial-step${index===tutorialStep?' active':''}${index<tutorialStep?' done':''}`;button.setAttribute('aria-label',`Step ${index+1}: ${item.title}`);button.setAttribute('aria-current',index===tutorialStep?'step':'false');button.textContent=String(index+1).padStart(2,'0');button.addEventListener('click',()=>{tutorialStep=index;renderTutorial();});$('tutorialSteps').append(button);});}
function openTutorial(startRun=false){tutorialStartsRun=startRun;tutorialStep=0;renderTutorial();$('tutorialDialog').showModal();buttonTone();}
function finishTutorial(startRun){profile.seenTutorial=true;saveProfile(profile);$('tutorialDialog').close();if(startRun){const index=nextSongIndex();selectedDifficulty=highestDifficulty(songs[index]);prepareRun(songs[index],selectedDifficulty);}}
function showProgress(fraction){const progress=document.querySelector('.loader-progress em');if(progress)progress.style.width=`${Math.floor(fraction*100)}%`;}
async function prepareRun(song,diff,{program=programForSong(song),runMode='campaign',dateKey=''}={}){
  simulationController?.abort();simulationController=null;const taskId=++preparationId;pauseAt=0;selectedSong=song;selectedDifficulty=diff;currentProgram=program;mode=runMode;dailyDate=dateKey;simResult=null;chart=null;
  const cacheKey=`${runMode}:${song.id}:${diff}:${program.seed}`;$('difficultyDialog').close();$('homeScreen').hidden=true;$('gameScreen').hidden=false;stopMenuHum();$('gameSong').textContent=song.title.toUpperCase();$('gameChapter').textContent=runMode==='daily'?`DAILY BRAIN · ${dateKey}`:`CHAPTER ${song.chapter}`;$('difficultyBadge').textContent=`${DIFFICULTIES[diff].label} · ${DIFFICULTIES[diff].lanes} LANES`;$('laneLabel').textContent=LANE_KEYS.slice(0,DIFFICULTIES[diff].lanes).map(k=>k.toUpperCase()).join(' · ');$('keyHint').textContent=LANE_KEYS.slice(0,DIFFICULTIES[diff].lanes).map(k=>k.toUpperCase()).join('   ');$('objectiveText').textContent=song.objective.text;
  const cached=runCache.get(cacheKey);if(cached){simResult=cached.sim;chart=cached.chart;await beginPlay();return;}
  $('retryButton').disabled=true;$('runSongLoader')?.remove();const loader=document.createElement('div');loader.id='runSongLoader';loader.className='simulation-loader';loader.innerHTML='<span class="loader-orb"></span><b>LISTENING TO THE CONNECTOME</b><span>Simulating neural activity → building your chart</span><i class="loader-progress"><em></em></i>';document.querySelector('.stage-wrap').append(loader);
  simulationController=new AbortController();try{simResult=await runSimulation(circuitJson,program,showProgress,{signal:simulationController.signal});if(taskId!==preparationId)return;chart=generateChart({circuit,sim:simResult,songId:song.id,difficulty:diff,bpm:song.bpm,durationMs:song.durationMs});runCache.set(cacheKey,{sim:simResult,chart});loader.remove();await beginPlay();}
  catch(error){if(taskId!==preparationId)return;loader.remove();$('gameScreen').hidden=true;$('homeScreen').hidden=false;toast(error.message);startMenuHum();}
}
function objectiveMet(){if(!engine||!selectedSong?.objective)return false;const o=selectedSong.objective;if(o.type==='combo')return engine.maxCombo>=o.value;if(o.type==='accuracy')return accuracy(engine)>=o.value;if(o.type==='noMiss')return engine.miss===0;return false;}
async function beginPlay(){unlockAudio();if(profile.settings.volume===0)setVolume(0);else setVolume(profile.settings.volume/100);engine=createEngine({chart,difficulty:selectedDifficulty,settings:{assist:profile.settings.assist}});syncAssistButton();objectiveDone=false;coachSeen={};stageParticles=[];hitFlash=Array(chart.laneCount).fill(0);$('scoreValue').textContent='000000';$('comboValue').innerHTML='0<span>×</span>';$('healthLabel').textContent='100%';$('healthBar').style.width='100%';$('accuracyValue').textContent='—%';$('noteCounter').textContent=`0 / ${chart.notes.length} NOTES`;$('retryButton').disabled=false;$('stage').setAttribute('aria-label',`Rhythm highway. Hit ${chart.laneCount} lanes using ${LANE_KEYS.slice(0,chart.laneCount).join(', ').toUpperCase()}.`);
  const pads=$('mobilePads');pads.replaceChildren();for(let lane=0;lane<chart.laneCount;lane++){const pad=document.createElement('button');pad.type='button';pad.textContent=LANE_KEYS[lane].toUpperCase();pad.setAttribute('aria-label',`Hit lane ${lane+1}`);pad.addEventListener('pointerdown',event=>{event.preventDefault();hitLane(lane);pad.classList.add('pressed');setTimeout(()=>pad.classList.remove('pressed'),100);});pads.append(pad);}startBacking(selectedSong.bpm);setLayers(0);songStartPerf=performance.now()+900;lastFrame=0;$('coachBubble').hidden=false;$('coachBubble').textContent=`FIRST SIGNAL INCOMING · Follow it to the lime line, then press ${LANE_KEYS.slice(0,chart.laneCount).map(k=>k.toUpperCase()).join(' / ')}.`;setTimeout(()=>{$('coachBubble').hidden=true;},4200);lastStageWidth=0;animationFrame=requestAnimationFrame(gameFrame);
}
function resizeCanvas(canvas,context){const rect=canvas.getBoundingClientRect(),dpr=Math.min(2,window.devicePixelRatio||1),w=Math.max(1,Math.round(rect.width*dpr)),h=Math.max(1,Math.round(rect.height*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;context.setTransform(dpr,0,0,dpr,0,0);return{width:rect.width,height:rect.height,changed:true};}return{width:rect.width,height:rect.height,changed:false};}
function buildGraphCache(w,h){const graph=document.createElement('canvas'),scale=Math.min(2,window.devicePixelRatio||1);graph.width=Math.round(w*scale);graph.height=Math.round(h*scale);const g=graph.getContext('2d');g.scale(scale,scale);g.clearRect(0,0,w,h);const nodes=circuitJson.neurons,edges=circuitJson.edges,skip=Math.max(1,Math.floor(edges.pre.length/2300));g.lineWidth=.55;for(let e=0;e<edges.pre.length;e+=skip){const a=edges.pre[e],b=edges.post[e],ax=22+nodes.x[a]*(w-44),ay=30+nodes.y[a]*(h-84),bx=22+nodes.x[b]*(w-44),by=30+nodes.y[b]*(h-84);g.strokeStyle=nodes.sign[a]<0?'rgba(255,120,181,.08)':'rgba(164,139,255,.095)';g.beginPath();g.moveTo(ax,ay);g.lineTo(bx,by);g.stroke();}const nodeStep=Math.max(1,Math.floor(nodes.x.length/450));for(let i=0;i<nodes.x.length;i+=nodeStep){const x=22+nodes.x[i]*(w-44),y=30+nodes.y[i]*(h-84);g.fillStyle=nodes.sign[i]<0?'rgba(255,120,181,.38)':'rgba(199,255,79,.25)';g.beginPath();g.arc(x,y,1.25,0,Math.PI*2);g.fill();}return graph;}
function gameFrame(now){if($('gameScreen').hidden||!engine)return;animationFrame=requestAnimationFrame(gameFrame);const box=resizeCanvas(stage,ctx),w=box.width,h=box.height;if(!w||!h)return;if(box.changed||w!==lastStageWidth||h!==lastStageHeight){graphCache=buildGraphCache(w,h);lastStageWidth=w;lastStageHeight=h;}
  const time=now-songStartPerf;if(time>=0){const missed=tick(engine,time,profile.settings.reduceMotion);for(const note of missed)onMiss(note.lane);if(engine.finished){finishRun(true);return;}if(time>=chart.leadInMs+chart.durationMs+400){finishRun(false);return;}}
  renderStage(w,h,time);renderHud(time);updateFly();}
function renderStage(w,h,time){ctx.clearRect(0,0,w,h);if(graphCache)ctx.drawImage(graphCache,0,0,w,h);ctx.fillStyle='rgba(9,10,19,.81)';ctx.fillRect(0,0,w,h);const laneCount=chart.laneCount,left=w*.15,right=w*.85,laneW=(right-left)/laneCount,top=42,bottom=h-73;for(let lane=0;lane<laneCount;lane++){const x=left+lane*laneW;ctx.fillStyle=`${LANE_COLORS[lane]}08`;ctx.fillRect(x,top,laneW,bottom-top);ctx.strokeStyle=`${LANE_COLORS[lane]}24`;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x,top);ctx.lineTo(x,bottom);ctx.stroke();ctx.fillStyle=`${LANE_COLORS[lane]}55`;ctx.font='10px Cascadia Code, monospace';ctx.textAlign='center';ctx.fillText(LANE_KEYS[lane].toUpperCase(),x+laneW/2,bottom+27);}
  ctx.strokeStyle='#ffffff1c';ctx.beginPath();ctx.moveTo(right,top);ctx.lineTo(right,bottom);ctx.stroke();const receptorY=bottom-26,approach=DIFFICULTIES[selectedDifficulty].approachMs;ctx.fillStyle='#c7ff4f18';ctx.fillRect(left,receptorY-3,right-left,7);ctx.strokeStyle='#c7ff4fbb';ctx.lineWidth=1.3;ctx.beginPath();ctx.moveTo(left,receptorY);ctx.lineTo(right,receptorY);ctx.stroke();for(let lane=0;lane<laneCount;lane++){const cx=left+(lane+.5)*laneW;const pulse=.22+Math.max(0,hitFlash[lane])*.5;ctx.fillStyle=`rgba(199,255,79,${pulse})`;ctx.beginPath();ctx.arc(cx,receptorY,7+Math.max(0,hitFlash[lane])*5,0,Math.PI*2);ctx.fill();hitFlash[lane]=Math.max(0,hitFlash[lane]-.045);}
  if(time<0){ctx.fillStyle='#c7ff4f';ctx.font='700 28px Cascadia Code, monospace';ctx.textAlign='center';ctx.fillText(String(Math.max(1,Math.ceil(-time/450))),w/2,h*.35);}for(const note of engine.notes){if(note.judged)continue;const until=note.t-time;if(until>approach||until< -190)continue;const y=receptorY-(until/approach)*(receptorY-top),x=left+(note.lane+.5)*laneW,r=Math.max(7,laneW*.21),fade=until<0?Math.max(.22,1+until/190):Math.min(1,(approach-until)/220+.2);ctx.globalAlpha=fade;ctx.fillStyle=LANE_COLORS[note.lane];ctx.shadowColor=LANE_COLORS[note.lane];ctx.shadowBlur=8+note.strength*10;ctx.beginPath();if(note.sign<0){ctx.moveTo(x,y-r);ctx.lineTo(x+r,y);ctx.lineTo(x,y+r);ctx.lineTo(x-r,y);ctx.closePath();}else{ctx.roundRect(x-r,y-r*.62,r*2,r*1.24,5);}ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#11121a';ctx.globalAlpha=.84;ctx.fillRect(x-1,y-r*.45,2,r*.9);ctx.globalAlpha=1;}
  if(!profile.settings.reduceMotion){for(let i=stageParticles.length-1;i>=0;i--){const p=stageParticles[i];p.life-=.04;p.x+=p.vx;p.y+=p.vy;p.vy-=.018;ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.r*p.life,0,Math.PI*2);ctx.fill();if(p.life<=0)stageParticles.splice(i,1);}ctx.globalAlpha=1;}const elapsed=Math.max(0,time-chart.leadInMs),seconds=Math.floor(elapsed/1000);$('songClock').textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;}
function renderHud(time){const acc=accuracy(engine),judged=engine.judgedCount;$('scoreValue').textContent=String(engine.score).padStart(6,'0');$('comboValue').innerHTML=`${engine.combo}<span>×</span>`;$('healthLabel').textContent=`${Math.round(engine.health)}%`;$('healthBar').style.width=`${engine.health}%`;$('accuracyValue').textContent=judged?`${acc.toFixed(1)}%`:'—%';$('noteCounter').textContent=`${judged} / ${chart.notes.length} NOTES`;
  const layers=activeLayers(engine.combo);document.querySelectorAll('#layerDisplay span:not(:first-child)').forEach((el,index)=>el.classList.toggle('unlocked',index<layers));if(engine.combo>0&&[10,25,50,100].includes(engine.combo)&&engine.combo!==renderHud.lastMilestone){renderHud.lastMilestone=engine.combo;showMilestone(engine.combo);}if(engine.combo===0)renderHud.lastMilestone=0;
  if(!coachSeen.approach&&engine.notes.some(n=>!n.judged&&n.t-time<DIFFICULTIES[selectedDifficulty].approachMs&&n.t-time>0)){coachSeen.approach=true;coach('Follow the signal into the lime target · Perfect ±45 ms · Good ±150 ms.');}
  if(!objectiveDone&&objectiveMet()){objectiveDone=true;$('objectiveText').textContent=`✓ ${selectedSong.objective.text}`;$('objectiveText').style.color='var(--lime)';playMilestone();toast('OBJECTIVE COMPLETE · BONUS STAR SECURED');}}
function coach(message){const bubble=$('coachBubble');bubble.textContent=message;bubble.hidden=false;clearTimeout(coach.timer);coach.timer=setTimeout(()=>bubble.hidden=true,2900);}
function showJudgement(kind,lane,error=0){const el=$('judgement');el.textContent=kind==='perfect'?'PERFECT':kind==='great'?'GREAT':kind==='good'?'GOOD':'MISS';el.className=`judgement${kind==='good'?' good':kind==='miss'?' miss':''}`;el.style.color=kind==='perfect'?LANE_COLORS[lane]:'';void el.offsetWidth;el.classList.add('show');hitFlash[lane]=1;}
function showMilestone(combo){const el=$('milestone');el.textContent=`✦ NEURAL SYNC · ${combo}× ✦`;el.classList.remove('show');void el.offsetWidth;el.classList.add('show');playMilestone();if(!profile.settings.reduceMotion)for(let i=0;i<12;i++)stageParticles.push({x:stage.clientWidth*.5,y:stage.clientHeight*.45,vx:Math.cos(i*Math.PI/6)*2.4,vy:Math.sin(i*Math.PI/6)*2.4,life:1,r:2.2,color:LANE_COLORS[i%4]});}
function hitLane(lane){if(!engine||engine.finished||$('gameScreen').hidden||pauseAt)return;const now=performance.now()-songStartPerf,result=hit(engine,lane,now,Number(profile.settings.offset)||0);if(result.kind==='empty')return;if(result.kind==='none')return;playJudgement(result.kind,lane);setLayers(engine.combo);showJudgement(result.kind,lane,result.error);if(result.kind==='perfect'||result.kind==='great'||result.kind==='good'){if(!coachSeen.hit){coachSeen.hit=true;coach('Clean hit. Your timing is feeding the brain.');}if(engine.combo===5&&!coachSeen.combo){coachSeen.combo=true;coach('Five in sync — keep going to wake the backing layers.');}if(!profile.settings.reduceMotion)for(let i=0;i<7;i++){const angle=i*6.28/7;stageParticles.push({x:stage.clientWidth*(.15+(lane+.5)*.7/chart.laneCount),y:stage.clientHeight*.76,vx:Math.cos(angle)*(1.4+Math.random()),vy:Math.sin(angle)*(1.4+Math.random()),life:1,r:1.5+Math.random()*1.2,color:LANE_COLORS[lane]});}if(profile.settings.haptics&&navigator.vibrate)navigator.vibrate(8);}
  if(result.kind==='miss')onMiss(lane);}
function onMiss(lane){playJudgement('miss',lane);dropout();showJudgement('miss',lane);if(engine.missStreak===3)coach('A little turbulence. Breathe, find the next signal.');if(engine.health<25&&!profile.settings.reduceMotion)document.body.classList.add('low-health');else document.body.classList.remove('low-health');if(engine.health<=0&&!engine.assist)finishRun(true);}
function flyMoodNow(){return flyMood({combo:engine?.combo||0,missStreak:engine?.missStreak||0,health:engine?.health??100,wake:engine?.weightedHits/Math.max(1,chart?.notes.length||1)||0,failed:engine?.health<=0,finished:!!engine?.finished,msSinceLastMiss:performance.now()-songStartPerf-(engine?.lastMissAt||-Infinity)});}
function updateFly(){if(selectedSong){const mood=flyMoodNow();const label=mood==='asleep'?'DORMANT':mood.toUpperCase();document.querySelector('.specimen-live').innerHTML=`<i></i> ${label}`;}}
function drawFly(now){if(!flyCanvas)return;const dpr=Math.min(2,window.devicePixelRatio||1),rect=flyCanvas.getBoundingClientRect();if(flyCanvas.width!==Math.round(rect.width*dpr)||flyCanvas.height!==Math.round(rect.height*dpr)){flyCanvas.width=Math.round(rect.width*dpr);flyCanvas.height=Math.round(rect.height*dpr);}flyCtx.setTransform(dpr,0,0,dpr,0,0);const w=rect.width,h=rect.height,c=flyCtx,mood=engine&&!$('gameScreen').hidden?flyMoodNow():'asleep',beat=engine?.combo||0,energy=mood==='asleep'?.28:mood==='waking'?.5:mood==='ecstatic'?1:.72,bob=profile.settings.reduceMotion?0:Math.sin(now/340+(beat%4))*energy*4;c.clearRect(0,0,w,h);const x=w*.5,y=h*.51+bob,scale=Math.min(w/450,h/400);
  c.save();c.translate(x,y);c.scale(scale,scale);c.globalAlpha=.15+energy*.14;c.strokeStyle=mood==='asleep'?'#756c94':'#c7ff4f';c.lineWidth=1;c.beginPath();c.ellipse(0,0,105+energy*18,88+energy*16,Math.sin(now/1700)*.18,0,Math.PI*2);c.stroke();c.globalAlpha=1;
  const wing=Math.sin(now/(mood==='ecstatic'?22:90))*.33;c.fillStyle='#c7c1ff28';c.strokeStyle='#b8aaff65';c.lineWidth=1.3;c.beginPath();c.ellipse(-16,-19,34,12,-.62+wing,0,Math.PI*2);c.ellipse(17,-19,34,12,.62-wing,0,Math.PI*2);c.fill();c.stroke();
  c.fillStyle='#c7ff4f';c.shadowColor='#c7ff4f';c.shadowBlur=energy*15;c.beginPath();c.ellipse(0,6,33,18,-.14,0,Math.PI*2);c.fill();c.shadowBlur=0;c.fillStyle='#b9f73e';c.beginPath();c.ellipse(28,1,16,14,0,0,Math.PI*2);c.fill();c.fillStyle='#f1c7bd';c.beginPath();c.arc(37,-4,4,0,Math.PI*2);c.arc(26,-4,4,0,Math.PI*2);c.fill();c.fillStyle='#26222c';c.beginPath();c.arc(38,-4,1.8,0,Math.PI*2);c.arc(27,-4,1.8,0,Math.PI*2);c.fill();
  c.strokeStyle='#cadc85';c.lineWidth=2;c.beginPath();c.moveTo(24,-10);c.quadraticCurveTo(31,-32,39,-34+Math.sin(now/180)*3);c.moveTo(20,-11);c.quadraticCurveTo(23,-31,30,-37+Math.sin(now/200)*3);c.stroke();c.fillStyle='#c7ff4f';c.beginPath();c.arc(39,-34+Math.sin(now/180)*3,2,0,Math.PI*2);c.arc(30,-37+Math.sin(now/200)*3,2,0,Math.PI*2);c.fill();
  c.strokeStyle='#829c58';c.lineWidth=1.7;for(let i=0;i<3;i++){c.beginPath();c.moveTo(-8+i*15,18);c.lineTo(-19+i*16,32+(i%2)*4+bob);c.lineTo(-24+i*16,33+(i%2)*4+bob);c.stroke();}c.fillStyle='#8b6dd5';c.globalAlpha=.8;for(let i=0;i<7;i++){c.beginPath();c.arc(-13+i*4,-1+i*3,1.2,0,Math.PI*2);c.fill();}c.globalAlpha=1;
  if(mood==='asleep'){c.fillStyle='#c1b6e2';c.font='12px Cascadia Code, monospace';c.fillText('z',51,-28);c.font='9px Cascadia Code, monospace';c.fillText('z',59,-40);}c.restore();
}
function animateHero(){drawFly(performance.now());requestAnimationFrame(animateHero);}
function persistRun(runSummary){const key=selectedSong.id,diff=selectedDifficulty;const discovered=discover(profile,chart.laneInfo,circuitJson.neurons.cellType);profile=discovered.profile;const firstClear=!profile.cleared[key]?.[diff],oldStars=profile.stars[key]?.[diff]||0,oldBest=profile.bestScore||0;const cleared=runSummary.cleared,stars=cleared&&!engine.assist?Math.min(3,runSummary.stars+(objectiveDone?1:0)):0;profile.cleared[key]={...(profile.cleared[key]||{}),[diff]:cleared};profile.stars[key]={...(profile.stars[key]||{}),[diff]:Math.max(oldStars,stars)};const curveKey=`${key}:${diff}`,previous=profile.pbCurves[curveKey];if(cleared&&(!previous||runSummary.score>oldBest))profile.pbCurves[curveKey]=runSummary.scoreAfter;
  const xp=awardXp({accuracy:runSummary.accuracy/100,firstClear,newStarsGained:Math.max(0,stars-oldStars),newBestGrade:runSummary.score>oldBest,newDiscoveries:discovered.found.length});profile.xp+=Math.max(0,xp);profile.level=levelForXp(profile.xp);profile.bestScore=Math.max(oldBest,runSummary.score);profile.lifetime={...profile.lifetime,spikes:(profile.lifetime.spikes||0)+simResult.totalSpikes,songs:(profile.lifetime.songs||0)+1,notes:(profile.lifetime.notes||0)+runSummary.totalNotes,bestCombo:Math.max(profile.lifetime.bestCombo||0,runSummary.maxCombo),perfectRuns:(profile.lifetime.perfectRuns||0)+(cleared&&runSummary.miss===0&&runSummary.accuracy===100?1:0)};if(cleared)profile.failsInARow[curveKey]=0;else profile.failsInARow[curveKey]=(profile.failsInARow[curveKey]||0)+1;if(mode==='daily'&&cleared)profile=updateStreak(profile,dailyDate);const achievements=[...profile.achievements];for(const badge of ACHIEVEMENTS)if(!achievements.includes(badge.id)&&badge.test(profile))achievements.push(badge.id);const newlyEarned=achievements.filter(id=>!profile.achievements.includes(id));profile.achievements=achievements;saveProfile(profile);return{stars,found:discovered.found,xp,achievements:newlyEarned};}
function finishRun(failed=false){if(!engine||engine._ended)return;engine._ended=true;engine.finished=true;stopBacking();document.body.classList.remove('low-health');const result=summary(engine),reward=persistRun(result);$('gameScreen').hidden=false;$('resultDialog').showModal();$('resultChapter').textContent=`CHAPTER ${selectedSong.chapter}`;$('resultLine').textContent=result.cleared?'THE FLY IS STIRRING.':failed?'SIGNAL LOST. TRY AGAIN?':'A GOOD FIRST SPARK.';$('gradeValue').textContent=result.grade;$('gradeLabel').textContent=result.cleared?'NEURAL RESONANCE':'KEEP THE SIGNAL ALIVE';$('gradeValue').style.color=result.cleared?'var(--lime)':'var(--pink)';$('finalScore').textContent=fmt(result.score);$('bestScoreLine').textContent=result.score>=profile.bestScore?'NEW PERSONAL BEST':`BEST ${fmt(profile.bestScore)}`;$('finalAccuracy').textContent=`${result.accuracy.toFixed(1)}%`;$('finalCombo').textContent=fmt(result.maxCombo);$('finalNeurons').textContent=fmt(simResult.activeNeurons);$('finalSpikes').textContent=fmt(simResult.totalSpikes);$('resultStars').replaceChildren();for(let i=0;i<3;i++){const s=document.createElement('span');s.textContent='✦';if(i<reward.stars)s.className='earned';$('resultStars').append(s);}$('resultFact').textContent=`${selectedSong.fact} ${reward.found.length?`NEW ATLAS ENTRY: ${reward.found.slice(0,3).join(', ')}.`:''}`;$('nextSongButton').textContent=selectedSong.id==='storm'?'REPLAY FINAL SIGNAL  →':'NEXT SIGNAL  →';$('nextSongButton').disabled=!songs.some((song,index)=>song.id!==selectedSong.id&&canAccessSong(index));$('retryButton').disabled=false;$('resultRetry').focus();renderHome();if(reward.achievements.length)toast('NEW MEDAL UNLOCKED · VIEW CAREER');}
function retry(){if(!selectedSong)return;$('resultDialog').close();$('pauseDialog').close();$('gameScreen').hidden=false;prepareRun(selectedSong,selectedDifficulty,{program:currentProgram,runMode:mode,dateKey:dailyDate});}
function pause(){if($('gameScreen').hidden||!engine||engine.finished||pauseAt)return;pauseAt=performance.now();if(animationFrame)cancelAnimationFrame(animationFrame);stopBacking();$('pauseDialog').showModal();}
function resume(){if(!pauseAt)return;const paused=performance.now()-pauseAt;songStartPerf+=paused;pauseAt=0;$('pauseDialog').close();startBacking(selectedSong.bpm,Math.max(0,performance.now()-songStartPerf));animationFrame=requestAnimationFrame(gameFrame);}
function returnHome(){preparationId++;simulationController?.abort();simulationController=null;stopBacking();if(animationFrame)cancelAnimationFrame(animationFrame);pauseAt=0;engine=null;$('runSongLoader')?.remove();$('resultDialog').close();$('pauseDialog').close();$('gameScreen').hidden=true;$('homeScreen').hidden=false;renderHome();startMenuHum();}
function hitFromKey(event){if(event.repeat||event.altKey||event.ctrlKey||event.metaKey)return;const key=event.key.toLowerCase(),lane=LANE_KEYS.indexOf(key);if(lane>=0&&engine&&lane<chart.laneCount){event.preventDefault();hitLane(lane);}}
function setDialogClose(){document.querySelectorAll('[data-close]').forEach(button=>button.addEventListener('click',()=>$(button.dataset.close).close()));}
function openDaily(){const day=new Date().toISOString().slice(0,10),index=hashSeed(day)%songs.length,song={...songs[index],id:`daily_${day}`,title:`Daily · ${songs[index].title}`,chapter:'DAILY'};mode='daily';const program=programForSong(song,hashSeed(day,'daily-brain'));song.id=`daily_${day}`;buttonTone();prepareRun(song,'easy',{program,runMode:'daily',dateKey:day});}
function openStudio(){const select=$('studioGroup');select.replaceChildren();for(const[id,group]of Object.entries(circuitJson.groups)){const opt=document.createElement('option');opt.value=id;opt.textContent=group.label;select.append(opt);}buttonTone();$('studioDialog').showModal();}
function runStudio(){const date=new Date().toISOString().slice(0,10),shape=$('studioShape').value,intensity=Number($('intensitySlider').value)/100,group=$('studioGroup').value,song={...songs[0],id:`studio_${Date.now()}`,title:'Brain Studio',subtitle:'your custom stimulus',chapter:'STUDIO',story:'Your lab. Your signal. See what this circuit plays back.',fact:'Custom studio stimulus generated from this demo network.'},program=programForSong(song,hashSeed(group,shape,intensity,date),[{group,coverage:.85,intensity,shape,params:{periodBeats:2,duty:.4,pulses:3,pulseBeats:.2,restBeats:2,periodBeats:4}}]);$('studioDialog').close();profile.studioTrack=true;saveProfile(profile);prepareRun(song,'easy',{program,runMode:'studio'});}
function syncAssistButton(){const enabled=!!profile.settings.assist,button=$('assistButton');if(!button)return;button.textContent=enabled?'PRACTICE ON':'PRACTICE OFF';button.setAttribute('aria-pressed',String(enabled));button.title=enabled?'Wider timing · no game over · stars disabled':'Turn on wider timing and remove game over for practice';}
function setAssist(enabled,announce=true){updateSetting('assist',enabled);if(engine){engine.assist=enabled;if(enabled&&engine.health<=0)engine.health=25;}syncAssistButton();if(announce)toast(enabled?'PRACTICE MODE ON · STARS DISABLED':'PRACTICE MODE OFF');if(enabled)coach('Practice mode: wider timing, no game over, no stars.');}
function toggleAssist(){setAssist(!profile.settings.assist);}
function initializeSettings(){const s=profile.settings;$('volumeSlider').value=s.volume;$('reduceMotion').checked=!!s.reduceMotion;$('hapticsToggle').checked=!!s.haptics;$('practiceToggle').checked=!!s.assist;$('offsetSlider').value=s.offset;$('offsetValue').textContent=`${s.offset>0?'+':''}${s.offset} ms`;syncAssistButton();}
function updateSetting(field,value){profile.settings={...profile.settings,[field]:value};saveProfile(profile);if(field==='volume')setVolume(value/100);}
function resize(){if(!stage)return;const dpr=Math.min(2,window.devicePixelRatio||1),r=stage.getBoundingClientRect();stage.width=Math.max(1,Math.round(r.width*dpr));stage.height=Math.max(1,Math.round(r.height*dpr));ctx.setTransform(dpr,0,0,dpr,0,0);lastStageWidth=0;}

$('continueButton').addEventListener('click',()=>{buttonTone();if(!profile.seenTutorial){openTutorial(true);return;}const index=nextSongIndex();selectedDifficulty=highestDifficulty(songs[index]);prepareRun(songs[index],selectedDifficulty);});
$('startSongButton').addEventListener('click',()=>{buttonTone();prepareRun(selectedSong,selectedDifficulty);});
$('nextSongButton').addEventListener('click',()=>{const index=songs.findIndex((song,i)=>song.id!==selectedSong.id&&canAccessSong(i)&&!Object.values(profile.cleared[song.id]||{}).some(Boolean));if(index>=0){$('resultDialog').close();returnHome();openSong(songs[index],index);$('difficultyDialog').close();prepareRun(songs[index],highestDifficulty(songs[index]));}else retry();});
$('resultRetry').addEventListener('click',retry);$('retryButton').addEventListener('click',retry);$('pauseRetry').addEventListener('click',retry);$('pauseButton').addEventListener('click',pause);$('resumeButton').addEventListener('click',resume);$('backButton').addEventListener('click',returnHome);
$('assistButton').addEventListener('click',toggleAssist);$('practiceToggle').addEventListener('change',e=>setAssist(e.target.checked));
$('dailyButton').addEventListener('click',openDaily);$('studioButton').addEventListener('click',openStudio);$('playStudio').addEventListener('click',runStudio);$('intensitySlider').addEventListener('input',e=>$('intensityValue').textContent=`${e.target.value}%`);
$('tutorialPrev').addEventListener('click',()=>{tutorialStep=Math.max(0,tutorialStep-1);renderTutorial();buttonTone();});$('tutorialNext').addEventListener('click',()=>{tutorialStep=Math.min(tutorialSteps.length-1,tutorialStep+1);renderTutorial();buttonTone();});$('tutorialStart').addEventListener('click',()=>finishTutorial(true));$('tutorialSkip').addEventListener('click',()=>finishTutorial(tutorialStartsRun));$('tutorialClose').addEventListener('click',()=>finishTutorial(false));$('tutorialScience').addEventListener('click',()=>{$('tutorialDialog').close();$('howDialog').showModal();buttonTone();});
$('careerButton').addEventListener('click',()=>{renderCareer();$('careerDialog').showModal();buttonTone();});$('atlasButton').addEventListener('click',()=>{$('atlasDialog').showModal();buttonTone();});$('settingsButton').addEventListener('click',()=>{initializeSettings();$('settingsDialog').showModal();buttonTone();});$('howButton').addEventListener('click',()=>openTutorial(false));setDialogClose();
$('volumeSlider').addEventListener('input',e=>updateSetting('volume',Number(e.target.value)));$('reduceMotion').addEventListener('change',e=>updateSetting('reduceMotion',e.target.checked));$('hapticsToggle').addEventListener('change',e=>updateSetting('haptics',e.target.checked));$('offsetSlider').addEventListener('input',e=>{$('offsetValue').textContent=`${Number(e.target.value)>0?'+':''}${e.target.value} ms`;updateSetting('offset',Number(e.target.value));});
window.addEventListener('keydown',event=>{if(event.key==='Escape'){if(!$('gameScreen').hidden&&!$('pauseDialog').open&&!$('resultDialog').open){pause();}return;}if(['INPUT','TEXTAREA','SELECT','BUTTON'].includes(event.target.tagName))return;if(event.key.toLowerCase()==='r'&&!$('gameScreen').hidden){event.preventDefault();retry();return;}hitFromKey(event);});window.addEventListener('resize',resize);window.addEventListener('beforeunload',stopBacking);document.addEventListener('visibilitychange',()=>{if(document.hidden&&!$('gameScreen').hidden&&!$('pauseDialog').open&&!$('resultDialog').open)pause();});

try{const [circuitResponse,songsResponse]=await Promise.all([fetch('data/circuit.json'),fetch('data/songs_config.json')]);if(!circuitResponse.ok||!songsResponse.ok)throw new Error('Open Neuron Beat through its local server (npm run serve); browser modules do not run from file://.');circuitJson=await circuitResponse.json();circuit=buildCircuit(circuitJson);songs=(await songsResponse.json()).songs;if(circuitJson.meta.source!=='flywire')$('demoBanner').hidden=false;$('neuronCount').textContent=`${fmt(circuit.n)} CELLS`;$('continueButton').addEventListener('mouseenter',()=>{if(profile.settings.volume>0)buttonTone();},{once:true});renderHome();initializeSettings();$('gameScreen').hidden=true;document.body.classList.add('ready');animateHero();startMenuHum();
}catch(error){$('heroTitle').innerHTML='LAB<br><span>OFFLINE.</span>';toast(error.message);}

if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
