import {mkdir,writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {dirname,join} from 'node:path';
const root=join(dirname(fileURLToPath(import.meta.url)),'..'),out=join(root,'web','data','circuit.json');
const groupsConfig=[['olfactory_L','Smell · left','olfactory','L'],['olfactory_R','Smell · right','olfactory','R'],['visual_L','Vision · left','visual','L'],['visual_R','Vision · right','visual','R'],['mechanosensory_L','Touch · left','mechanosensory','L'],['mechanosensory_R','Touch · right','mechanosensory','R'],['gustatory_L','Taste · left','gustatory','L'],['gustatory_R','Taste · right','gustatory','R']],layers=[192,300,330,330,330,318],neurons=Object.fromEntries(['id','cellType','cls','superClass','side','sign','x','y','inDeg','outDeg'].map(k=>[k,[]])),groups={},pairs=new Map();let state=0x4e42544;
function random(max){state=(state+0x6d2b79f5)>>>0;let t=state;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);t^=t>>>14;return(t>>>0)%max;}
const starts=[];let base=0;
for(let layer=0;layer<layers.length;layer++){starts.push(base);for(let local=0;local<layers[layer];local++){const i=base+local;let side,cls,type,superClass,sign;if(layer===0){const groupIndex=Math.floor(local/24),[, ,modality,gside]=groupsConfig[groupIndex];side=gside;cls=modality;superClass='sensory';type=`DEMO_${modality.toUpperCase()}_RECEPTOR_${String(local%24+1).padStart(2,'0')}`;sign=local%5===0?-1:1;}else{side=local%2?'R':'L';cls=['projection','interneuron','descending','motor','local'][layer-1];superClass='central';type=`DEMO_${cls.toUpperCase()}_${String(local%60+1).padStart(2,'0')}`;sign=(local*7+layer*3)%5===0?-1:1;}for(const[k,v]of Object.entries({id:`DEMO_${String(i).padStart(5,'0')}`,cellType:type,cls,superClass,side,sign,x:+(layer/(layers.length-1)).toFixed(5),y:+((local+.5)/layers[layer]).toFixed(5),inDeg:0,outDeg:0}))neurons[k].push(v);}if(layer===0)for(let g=0;g<groupsConfig.length;g++){const[id,label,modality,side]=groupsConfig[g];groups[id]={label,modality,side,neurons:Array.from({length:24},(_,j)=>g*24+j)};}base+=layers[layer];}
for(let layer=1;layer<layers.length;layer++){const prevStart=starts[layer-1],currStart=starts[layer],prevN=layers[layer-1];for(let local=0;local<layers[layer];local++){const post=currStart+local,picked=new Set();while(picked.size<(layer===1?5:4))picked.add(prevStart+random(prevN));for(const pre of picked)pairs.set(`${pre},${post}`,7+random(13));}if(layer>1)for(let local=0;local<layers[layer];local+=3){const pre=starts[layer-2]+(local*11+layer*17)%layers[layer-2];pairs.set(`${pre},${currStart+local}`,6+random(9));}}
const edges={pre:[],post:[],syn:[]};for(const [key,weight]of[...pairs].sort((a,b)=>{const[ap,aq]=a[0].split(',').map(Number),[bp,bq]=b[0].split(',').map(Number);return ap-bp||aq-bq;})){const[pre,post]=key.split(',').map(Number);edges.pre.push(pre);edges.post.push(post);edges.syn.push(weight);neurons.outDeg[pre]++;neurons.inDeg[post]++;}
const data={meta:{source:'synthetic-demo',dataset:'Neuron Beat deterministic synthetic teaching network v1',generatedAt:'deterministic build',counts:{neurons:base,edges:edges.pre.length,seeds:layers[0],unknownNt:0,inhibitory:neurons.sign.filter(x=>x<0).length},minSyn:5},neurons,edges,groups};await mkdir(join(root,'web','data'),{recursive:true});await writeFile(out,JSON.stringify(data));console.log(`Built explicitly synthetic demo: ${base} neurons, ${edges.pre.length} edges, ${Object.keys(groups).length} stimulus groups`);
